# Generated by Django 2.2 on 2022-10-21 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='left_pannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=10)),
                ('for_user', models.IntegerField()),
                ('for_owner', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('Phone', models.IntegerField()),
                ('Email', models.CharField(max_length=20)),
                ('last_login_time', models.DateTimeField(auto_now_add=True)),
                ('auth_token', models.CharField(default='', max_length=50)),
                ('is_owner', models.IntegerField()),
                ('is_user', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='e_wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User_Auth')),
            ],
        ),
    ]
