# Generated by Django 2.2 on 2022-10-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_auth_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_auth',
            name='gst_num',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user_auth',
            name='login_status',
            field=models.BooleanField(default=False),
        ),
    ]
