# Generated by Django 2.2 on 2022-10-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20221021_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_wallet',
            name='wallet_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_auth',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='user_auth',
            name='last_login_time',
            field=models.CharField(default='', max_length=20),
        ),
    ]
