# Generated by Django 2.2 on 2022-10-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20221025_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_auth',
            name='Phone',
            field=models.IntegerField(null=True),
        ),
    ]
