# Generated by Django 2.2 on 2022-10-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20221025_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_auth',
            name='Email',
            field=models.CharField(max_length=50),
        ),
    ]
