# Generated by Django 2.2 on 2022-10-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20221025_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_auth',
            name='is_owner',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_auth',
            name='is_user',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
