# Generated by Django 2.2 on 2022-10-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20221025_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_auth',
            name='profile_status',
            field=models.BooleanField(default=False),
        ),
    ]
