# Generated by Django 2.2 on 2022-10-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20221026_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_wallet',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
