# Generated by Django 2.2 on 2022-10-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20221027_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loggeduser', models.CharField(default='', max_length=20)),
                ('auth_token', models.CharField(default='', max_length=50)),
                ('userid', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user_auth',
            name='auth_token',
        ),
        migrations.RemoveField(
            model_name='user_auth',
            name='last_login_time',
        ),
        migrations.RemoveField(
            model_name='user_auth',
            name='login_status',
        ),
    ]
