# Generated by Django 2.2 on 2022-10-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20221027_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_auth',
            name='is_user',
            field=models.IntegerField(null=True),
        ),
    ]
