# Generated by Django 2.2 on 2022-10-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20221027_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='left_pannel',
            name='field',
            field=models.CharField(max_length=30),
        ),
    ]
