# Generated by Django 2.2 on 2022-10-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20221027_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='left_pannel',
            name='icons',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='left_pannel',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
