# Generated by Django 2.2 on 2022-10-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20221027_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_auth',
            name='is_owner',
        ),
        migrations.RemoveField(
            model_name='user_auth',
            name='is_user',
        ),
        migrations.AddField(
            model_name='user_auth',
            name='who',
            field=models.CharField(default='', max_length=10),
        ),
    ]
