# Generated by Django 2.2 on 2022-10-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20221028_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='left_pannel',
            name='url',
            field=models.CharField(default='', max_length=30),
        ),
    ]
