# Generated by Django 2.2 on 2022-10-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20221028_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_auth',
            name='Name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
