# Generated by Django 2.2 on 2022-10-28 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20221028_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_wallet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User_Auth'),
        ),
    ]
